# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy to tc-light

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: ssh-pipeline
      uses: cross-the-world/ssh-pipeline@v1.2.0
      with:
        host: ${{ secrets.SSH_IP }}
        user: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          ps -ef | grep app.js | grep -v grep | awk '{print $2}' | xargs kill -9
          cd /home/ubuntu/blog 
          git pull origin main
          yarn build
          screen -r blog
          yarn start
          
